---

- name: Set ntp_service_name fact
  set_fact:
    ntp_service_name: "{{ item }}"
  with_items: "{{ { 'Debian':'ntp', 'RedHat':'ntpd' } [ansible_os_family] | default('') }}"

- name: Set ntp_config_driftfile fact
  set_fact:
    ntp_config_driftfile: "{{ item }}"
  with_items: "{{ { 'Debian':'/var/lib/ntp/ntp.drift', 'RedHat':'/var/lib/ntp/drift' } [ansible_os_family] | default('') }}"

- name: Install the NTP package
  package:
    name: "ntp"
    state: present

- name: Copy the ntp.conf template file
  template:
    src: "ntp.conf.j2"
    dest: "/etc/ntp.conf"
  notify:
   - restart ntp

- name: Start and enable NTP service
  service:
    name: "{{ ntp_service_name }}"
    state: started
    enabled: yes
