---

- include: redis_packages.yml

- name: Deploy Redis instances configurations
  include: redis_configs.yml
  with_items:
    - "{{ redis_instances }}"
  loop_control:
    loop_var: redis_instance

- name: Ensure Redis instances are started and enabled
  include: redis_services.yml
  with_items:
    - "{{ redis_instances }}"
  loop_control:
    loop_var: redis_instance

- name: Check and configure clusters
  include: redis_clusters.yml
  with_items:
    - "{{ redis_clusters }}"
  loop_control:
    loop_var: redis_cluster
