---

- block:
    - name: "Get Redis cluster status"
      command: "redis-cli --cluster check {{ redis_cluster.nodes[0].master }}"
      failed_when: false
      changed_when: false
      register: redis_cluster_status

    - block:
        - name: "Create Redis cluster, if needed"
          shell: |
            echo yes |
            redis-cli --cluster create \
            {% for node in redis_cluster.nodes %}{{ node.master }}{% if not loop.last %} {% endif %}{% endfor %}

        - name: "Add Redis slave nodes"
          shell: |
            MASTER_ID=$(redis-cli cluster nodes | grep {{ item.master }} | cut -f 1 -d " ")
            {% for slave in item.slaves %}
            echo yes | redis-cli --cluster add-node {{ slave }} {{ item.master }} --cluster-slave --cluster-master-id $MASTER_ID
            {% endfor %}
          with_items:
            - "{{ redis_cluster.nodes }}"
      when:
        - redis_cluster_status.rc != 0
  run_once: true
