---

- name: "Check Redis service - {{ redis_instance.name }} instance"
  service:
    name: "redis_{{ redis_instance.name }}"
    state: "{{ redis_instance.state }}"
    enabled: "{{ redis_instance.enabled }}"

- name: "Check Redis exporter service - {{ redis_instance.name }} instance"
  service:
    name: "redis_{{ redis_instance.name }}_exporter.service"
    state: "{{ redis_instance.exporter_state }}"
    enabled: "{{ redis_instance.exporter_enabled }}"
  when:
    - redis_instance.exporter_enabled | bool

- name: "Check if Redis {{ redis_instance.bind }}:{{ redis_instance.port }} instance {{ redis_instance.name }} is reachable"
  wait_for:
    host: "{{ redis_instance.bind }}"
    port: "{{ redis_instance.port }}"
    state: started
