---

- block:
    - name: Adding EPEL yum repository
      package:
        name:
          - epel-release
          - yum-utils
          - "{{ redis_RedHat_remi_package }}"

    - name: Check if remi repository is enabled
      shell: |
        set -o pipefail
        yum clean expire-cache
        yum repolist enabled | grep ^remi
      register: remi_repository_is_enabled
      changed_when: false
      failed_when: false

    - name: Enable remi repository
      command: 'yum-config-manager --enable remi'
      when:
        - remi_repository_is_enabled.rc != 0
  when:
    - ansible_os_family == "RedHat"

- name: Ensure Redis is installed
  package:
    name:
      - "{{ lookup('vars', 'redis_' + ansible_os_family + '_package') }}"
    state: "present"

- block:
    - name: "Check for {{ redis_exporter_bin }} existence under /usr/local/bin/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}"
      stat:
        path: "/usr/local/bin/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}/redis_exporter"
      register: redis_exporter_bin_stat

    - name: "Check for {{ redis_exporter_bin }} link existence"
      stat:
        path: "{{ redis_exporter_bin }}"
      register: redis_exporter_link_stat

    - block:
        - name: Download redis_exporter package
          get_url:
            url: "{{ redis_exporter_download_url }}"
            dest: "/tmp/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}.tar.gz"

        - name: Unarchive redis_exporter binary from downloaded package
          unarchive:
            src: "/tmp/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}.tar.gz"
            dest: "/usr/local/bin"
            remote_src: yes

        - name: Remove redise_exporter downloaded archive
          file:
            path: "/tmp/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}.tar.gz"
            state: absent

        - name: "Create redis_exporter executable into {{ redis_exporter_bin }}"
          file:
           src: "/usr/local/bin/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}/redis_exporter"
           dest: "{{ redis_exporter_bin }}"
           force: yes
           state: link
      when:
        - redis_exporter_bin_stat.stat.executable is not defined or
          not redis_exporter_bin_stat.stat.executable | bool or
          redis_exporter_link_stat.stat.islnk is not defined or
          not redis_exporter_link_stat.stat.islnk | bool
  when:
    redis_exporter_enable | bool
