---

mongodb_version: '4.2'
mongodb_repository: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/$basearch/"
mongodb_packages:
  - mongodb-org

# Generic variables
mongodb_user: "mongod"
mongodb_group: "mongod"

# Config Server specific variables
mongodb_cs_config_file: "/etc/mongod-cs.conf"
mongodb_cs_bind_ip: "127.0.0.1"
mongodb_cs_port: 27019
mongodb_cs_dbpath: "/var/lib/mongo/cs"
mongodb_cs_wired_tiger_enable: false
mongodb_cs_wired_tiger_cache_size: ''
mongodb_cs_logpath: "/var/log/mongodb"
mongodb_cs_pidfilepath: "/var/run/mongodb"
mongodb_cs_replica_set_name: "csReplSet"

# Query Router specific variables
mongodb_qr_config_file: "/etc/mongos-qr.conf"
mongodb_qr_logpath: "/var/log/mongodb"
mongodb_qr_bind_ip: "127.0.0.1"
mongodb_qr_port: 27017
mongodb_qr_pidfilepath: "/var/run/mongodb"

# Shard Node specific variables
mongodb_sn_config_file: "/etc/mongod-sn.conf"
mongodb_sn_bind_ip: "127.0.0.1"
mongodb_sn_port: 27018
mongodb_sn_dbpath: "/var/lib/mongo/sn"
mongodb_sn_wired_tiger_enable: false
mongodb_sn_wired_tiger_cache_size: ''
mongodb_sn_logpath: "/var/log/mongodb"
mongodb_sn_pidfilepath: "/var/run/mongodb"
mongodb_sn_replica_set_name: "shard-rs0"
