---

- name: "Power: Get VMs status"
  azure.azcollection.azure_rm_virtualmachine_info:
    name: "{{ vm.split('.')[0] }}"
    resource_group: "{{ azure_resource_group_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant_id }}"
  register: vms_state
  changed_when: false
  delegate_to: localhost
  loop: "{{ vm_list }}"
  loop_control:
    loop_var: vm

- name: "Power: Power on VMS"
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ vm.vms[0].name }}"
    resource_group: "{{ azure_resource_group_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant_id }}"
  loop: "{{ vms_state.results }}"
  changed_when: false
  loop_control:
    loop_var: vm
  when:
    - vm.vms[0].power_state == 'deallocated'
  delegate_to: localhost
  register: azure_power_on_async_results
  async: 600
  poll: 0

- name: "Wait for VMs to be reachable via ssh"
  wait_for:
    port: 22
    host: "{{ vm }}"
    search_regex: OpenSSH
  connection: local
  loop: "{{ vm_list }}"
  loop_control:
    loop_var: vm
  retries: 60
  delay: 10
