---

- name: "Power: Load all variables"
  include_vars:
    file: "{{ ansible_inventory_sources[0] }}/group_vars/all.yaml"
  register: global_vars
  changed_when: false
  delegate_to: localhost

- name: "Power: Load VMs variables"
  include_vars:
    file: "{{ ansible_inventory_sources[0] }}/host_vars/{{ vm }}.yaml"
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
  register: vms_vars
  changed_when: false
  delegate_to: localhost

- name: "Power: Power off VMs"
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ vm_var.vm.split('.')[0] }}"
    allocated: no
    resource_group: "{{ azure_resource_group_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant_id }}"
  loop: "{{ vms_vars.results }}"
  loop_control:
    loop_var: vm_var
  changed_when: false
  when:
    - global_vars.ansible_facts.azure_vm_keep_running is defined
    - not global_vars.ansible_facts.azure_vm_keep_running
    - vm_var.ansible_facts.azure_vm_keep_running is not defined or
      not vm_var.ansible_facts.azure_vm_keep_running
  delegate_to: localhost
  register: azure_power_off_async_results
  async: 600
  poll: 0

- name: "Wait for VMs to be unreachable"
  wait_for:
    port: 22
    host: "{{ vm_var.vm }}"
    state: stopped
  connection: local
  loop: "{{ vms_vars.results }}"
  loop_control:
    loop_var: vm_var
  retries: 60
  delay: 10
  when:
    - global_vars.ansible_facts.azure_vm_keep_running is defined
    - not global_vars.ansible_facts.azure_vm_keep_running
    - vm_var.ansible_facts.azure_vm_keep_running is not defined or
      not vm_var.ansible_facts.azure_vm_keep_running
