---


# If status: on, power on the VMs
- name: Power on VM
  include_tasks: power_on.yaml
  vars:
    vms: "{{ vm_list }}"
  when:
    - status

# If status: off, power off the VMs
- name: Power off VM
  include_tasks: power_off.yaml
  vars:
    vms: "{{ vm_list }}"
    vms_state: "{{ vms_state.results }}"
  when:
    - not status
