---

- name: "Power: Power off VMs"
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ vm.split('.')[0] }}"
    allocated: no
    resource_group: "{{ azure_resource_group_name }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant_id }}"
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
  changed_when: false
  when:
    - hostvars[vm].azure_vm_keep_running is defined
    - not hostvars[vm].azure_vm_keep_running
  delegate_to: localhost
  register: azure_power_off_async_results
  async: 600
  poll: 0

- name: "Wait for VMs to be unreachable"
  wait_for:
    port: 22
    host: "{{ vm }}"
    state: stopped
  connection: local
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
  retries: 60
  delay: 10
  when:
    - hostvars[vm].azure_vm_keep_running is defined
    - not hostvars[vm].azure_vm_keep_running
  delegate_to: localhost
