# graylog.yml
---
- hosts: logmaster
  become: True
  tasks:
  - import_role:
      name: 'Graylog2.graylog-ansible-role'
    vars:
      es_instance_name: 'graylog'
      es_scripts: False
      es_templates: False
      es_version_lock: False
      es_heap_size: 1g

      es_config: {
        node.name: "graylog",
        cluster.name: "graylog",
        discovery.zen.ping.unicast.hosts: "localhost:9301",
        http.port: 9200,
        transport.tcp.port: 9300,
        network.host: 0.0.0.0,
        node.data: true,
        node.master: true,
        bootstrap.mlockall: false,
        discovery.zen.ping.multicast.enabled: false
      }
      graylog_web_endpoint_uri: 'http://127.0.0.1:9000/api/'
  
      nginx_sites:
        graylog:
          - listen 80 default_server
          - server_name graylog.local.mobytgroup.com
          - location / {
            proxy_pass                    http://127.0.0.1:9000/;
            proxy_set_header              Host $host;
            proxy_set_header              X-Real-IP $remote_addr;
            proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header              X-Forwarded-Server $host;
            proxy_set_header              X-Graylog-Server-URL http://graylog.local.mobytgroup.com/api;
            proxy_pass_request_headers    on;
            proxy_connect_timeout         150;
            proxy_send_timeout            100;
            proxy_read_timeout            100;
            proxy_buffers                 4 32k;
            client_max_body_size          8m;
            client_body_buffer_size       128k; 
            }

  #import_role:
  #    name: 'Graylog2.graylog-ansible-role'
  tags: graylog
