---

# Configurations for all servers
- hosts: graylog
  become: true
  tasks:
    - import_role:
        name: 'system'

    - import_tasks: 'roles/graylog-server/tasks/common.yml'

# Configurations for backend servers
- hosts: graylog_backend
  become: true
  tasks:
    - import_role:
        name: 'mongodb-cluster'

    - import_role:
        name: 'ansible-elasticsearch'

    - import_role:
        name: 'graylog-server'

# Configurations for frontend servers
- hosts: graylog_frontend
  become: true
  tasks:
    - import_role:
        name: 'nginx'

    - import_role:
        name: 'keepalived'
