---

# Configurations for all servers
- hosts: graylog
  become: true
  tasks:
    - import_role:
        name: 'selinux'

    - name: Install Tuned-adm in RedHat
      yum:
         name: tuned
         state: present
    - name: Make folder for profile no-thp
      file:
         name: /etc/tuned/no-thp
         state: directory
         owner: root
         group: root
    - name: Copy no-thp profile's File
      copy: 
        src: '{{ item.src }}'
        dest: "/etc/tuned/no-thp"
        owner: root
        group: root
        mode: 0755
      with_filetree:
          - 'files/no-thp/'
    - name: Start no-thp Proifle
      command: "tuned-adm profile no-thp"
    - name: Import Configuration swappiness
      sysctl:
        name: vm.swappiness
        value: 20
        state: present
        reload: yes
        sysctl_set: yes
    - name: Import Configuration for tcp keepalive
      sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: 300
        state: present
        reload: yes
        sysctl_set: yes
    - copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes

## Configurations for backend servers
- hosts: be-graylog
  become: true
  vars:
    # Configurations for ElasticSearch cluster
    es_version: "2.4.5"
    es_cluster_name: "graylog-es-cluster"
    es_instance_name: "graylog-es-cluster1"
    es_scripts: False
    es_templates: False
    es_version_lock: False
    es_heap_size: 256m
    es_data_dirs: "/store/elasticsearch/data"
    es_log_dir: "/store/elasticsearch/log"
    es_work_dir: "/store/elasticsearch/tmp"
    es_bulk_queue_size: -1

    es_config: {
      discovery.zen.ping.unicast.hosts: "{{ es_cluster_interconnect_nodes }}",
      cluster.name: "graylog-es-cluster",
      network.host: "{{ ansible_eth0.ipv4.address }}, _local_",
      transport.host: "{{ interconnect_addr }}",
      discovery.zen.ping.multicast.enabled: false,
      http.port: 9200,
      transport.tcp.port: 9300,
      node.data: true,
      node.master: true,
      bootstrap.mlockall: false,
      index.number_of_shards: 3,
      index.number_of_replicas: 3
    }

    # Configurations for MongoDB cluster
    ## Config Server
    mongodb_cs_bind_ip: "{{ interconnect_addr }}"
    mongodb_cs_logpath: "/store/mongodb/cs/log"
    mongodb_cs_dbpath: "/store/mongodb/cs/data"
    mongodb_cs_replica_set_name: "configReplSet"
    ## Query Router
    mongodb_qr_bind_ip: "{{ interconnect_addr }}"
    mongodb_qr_logpath: "/store/mongodb/qr/log"
    mongodb_qr_rs_nodes: "{{ mdb_replica_set_nodes }}"
    ## Shard Node
    mongodb_sn_bind_ip: "{{ interconnect_addr }}"
    mongodb_sn_logpath: "/store/mongodb/sn/log"
    mongodb_sn_dbpath: "/store/mongodb/sn/data"
    mongodb_sn_replica_set_name: "graylog-shard-rs0"

    # Configurations for Graylog Server
    graylog_server_rest_listen_ip: "{{ ansible_eth0.ipv4.address }}"
    graylog_server_web_listen_ip: "{{ ansible_eth0.ipv4.address }}"
    graylog_server_password_secret: "2jueVqZpwLLjaWxV"
    graylog_server_admin_password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_server_timezone: 'Europe/Rome'
    graylog_server_elasticsearch_cluster_name: "{{ es_cluster_name }}"
    graylog_server_elasticsearch_discovery_zen_ping_unicast_hosts: "{{ es_cluster_interconnect_nodes }}"
    graylog_server_mongodb_uri: "mongodb://{{ graylog_mdb_qr_set_nodes }}/graylog"
    graylog_server_message_journal_dir: '/store/graylog/journal'
    #graylog_server_processbuffer_processors: 32
    #graylog_server_outputbuffer_processors: 156
    #graylog_server_outputbuffer_processor_keep_alive_time: 5000
    #graylog_server_outputbuffer_processor_threads_core_pool_size: 36
    #graylog_server_outputbuffer_processor_threads_max_pool_size: 156
    #graylog_server_min_heap: '2048m'
    #graylog_server_max_heap: '2048m'
  tasks:
    - import_role:
        name: 'mongodb-cluster'

    - import_role:
        name: 'ansible-elasticsearch'

    - import_role:
        name: 'graylog-server'

# Configurations for frontend servers
- hosts: fe-graylog
  become: True
  vars:
    # Nginx configuration
    nginx_http_name: logmaster
    nginx_http_port: 80
    nginx_graylog_port: 9000
    nginx_log_dir: /store/logs/nginx
    nginx_streams:
            #      - name: API_PORT
            #        port: 12900
            #        protocol: tcp
      - name: syslog_udp_5140
        port: 5140
        protocol: udp
        #      - name: syslog_udp_5141_dispatcherDLR
        #        port: 5141
        #        protocol: udp
        #      - name: syslog_udp_5240_antispam_log
        #        port: 5240
        #        protocol: udp
        #      - name: syslog_udp_5241_jsmpp_log
        #        port: 5241
        #        protocol: udp
        #      - name: syslog_udp_5242_ricezione_log
        #        port: 5242
        #        protocol: udp
        #      - name: syslog_udp_5243_sendsmart_error_log
        #        port: 5243
        #        protocol: udp
        #      - name: syslog_udp_5244_sendsmart_log
        #        port: 5244
        #        protocol: udp
        #      - name: syslog_udp_5245_gwsms_log
        #        port: 5245
        #        protocol: udp
        #      - name: syslog_udp_5246_mail2sms_log
        #        port: 5246
        #        protocol: udp
        #      - name: syslog_udp_5247_mocontactstopfr_log
        #        port: 5247
        #        protocol: udp
        #      - name: syslog_udp_5340_client_multileve_sendhttp_log
        #        port: 5340
        #        protocol: udp
        #      - name: syslog_udp_5341_credit_queue_log
        #        port: 5341
        #        protocol: udp
        #      - name: syslog_udp_5342_multifrance_sendhttp_log
        #        port: 5342
        #        protocol: udp
        #      - name: syslog_udp_5343_multilevel_sendhttp_log
        #        port: 5343
        #        protocol: udp
        #      - name: syslog_udp_5344_notify_log
        #        port: 5344
        #        protocol: udp
        #      - name: syslog_udp_5345_send_email_log
        #        port: 5345
        #        protocol: udp
        #      - name: syslog_udp_5346_smsftp_worker_log
        #        port: 5346
        #        protocol: udp
        #      - name: syslog_udp_5347_smssent_log
        #        port: 5347
        #        protocol: udp
        #      - name: syslog_udp_5440_notifysplit_log
        #        port: 5440
        #        protocol: udp
        #      - name: syslog_udp_5441_rx_log
        #        port: 5441
        #        protocol: udp
        #      - name: syslog_udp_5442_smsftp_scan_log
        #        port: 5442
        #        protocol: udp
        #      - name: syslog_udp_5443_checkricezione_log
        #        port: 5443
        #        protocol: udp
        #      - name: beats_input
        #        port: 5044
        #        protocol: tcp
        #      - name: Syslog_TCP_54514_HaProxy
        #        port: 54514
        #        protocol: tcp
        #      - name: Syslog_UDP_54516_Apache
        #        port: 54516
        #        protocol: udp
        #      - name: Syslog_UDP_54515_Postfix
        #        port: 54515
        #        protocol: udp
        #      - name: Syslog_UDP_54513_Syslog
        #        port: 54513
        #        protocol: udp
        #      - name: Syslog_UDP_54512_Nginx
        #        port: 54512
        #        protocol: udp
        #      - name: Syslog_TCP_54511_SSHD
        #        port: 54511
        #        protocol: tcp
        #      - name: Syslog_UDP_54510_Cron
        #        port: 54510
        #        protocol: udp
        #      - name: Syslog_UDP_54517_Mikrotik
        #        port: 54517
        #        protocol: udp
        #      - name: Syslog_UDP_5248-Protocol_log
        #        port: 5248
        #        protocol: udp
        #      - name: Syslog_UDP_5249-benchmark_log
        #        port: 5249
        #        protocol: udp
        #      - name: Syslog_UDP_5250-monitor_sms_log
        #        port: 5250
        #        protocol: udp
        #      - name: Syslog_UDP_5251-notify_check_log
        #        port: 5251
        #        protocol: udp
        #      - name: Syslog_UDP_5252-assiststop_log
        #        port: 5252
        #        protocol: udp
        #      - name: Syslog_UDP_5253-expire_credit_log
        #        port: 5253
        #        protocol: udp
        #      - name: Syslog_UDP_5254-mncbe_log
        #        port: 5254
        #        protocol: udp
        #      - name: Syslog_UDP_5255-billing_log
        #        port: 5255
        #        protocol: udp
        #      - name: Beats_tcp_5256_PureFTPD_log
        #        port: 5256
        #        protocol: tcp
        #      - name: Beats_tcp_5257_Squid_log
        #        port: 5257
        #        protocol: tcp
        #      - name: Syslog_UDP_25025-Relay_Inet
        #        port: 25025
        #        protocol: udp
        #      - name: Beats_tcp_5258_DNS_xferout.log
        #        port: 5258
        #        protocol: tcp
        #      - name: Beats_tcp_5259_DNS_xferin.log
        #        port: 5259
        #        protocol: tcp
        #      - name: Beats_tcp_5260_DNS_client.log
        #        port: 5260
        #        protocol: tcp
        #      - name: Beats_tcp_5261_DNS_config.log
        #        port: 5261
        #        protocol: tcp
        #      - name: Beats_tcp_5263_DNS_default.log
        #        port: 5263
        #        protocol: tcp
        #      - name: Beats_tcp_5264_DNS_dispatch.log
        #        port: 5264
        #        protocol: tcp
        #      - name: Beats_tcp_5265_DNS_dnssec.log
        #        port: 5265
        #        protocol: tcp
        #      - name: Beats_tcp_5266_DNS_general.log
        #        port: 5266
        #        protocol: tcp
        #      - name: Beats_tcp_5267_DNS_lameservers.log
        #        port: 5267
        #        protocol: tcp
        #      - name: Beats_tcp_5268_DNS_network.log
        #        port: 5268
        #        protocol: tcp
        #      - name: Beats_tcp_5269_DNS_notify.log
        #        port: 5269
        #        protocol: tcp
        #      - name: Beats_tcp_5270_DNS_queries.log
        #        port: 5270
        #        protocol: tcp
        #      - name: Beats_tcp_5271_DNS_resolver.log
        #        port: 5271
        #        protocol: tcp
        #      - name: Beats_tcp_5272_DNS_security.log
        #        port: 5272
        #        protocol: tcp
        #      - name: Beats_tcp_5273_DNS_unmatched.log
        #        port: 5273
        #        protocol: tcp
        #      - name: Beats_tcp_5274_DNS_update.log
        #        port: 5274
        #        protocol: tcp
        #      - name: Beats_tcp_5275_DNS_database.log
        #        port: 5275
        #        protocol: tcp
        #      - name: Syslog_UDP_5142_Comodo.log
        #        port: 5142
        #        protocol: udp


    nginx_be_servers: "{{ groups['be-graylog'] }}"

    # Keepalived configuration
    keepalived_vrrp_password: '91514409'
    keepalived_vrrp_vips: "{{ graylog_vips }}"


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted
  tasks:
    # Nginx
    - name: Install nginx
      package:
        name: nginx
        state: present
    - name: Create nginx log dir
      file:
        path: /store/logs/nginx
        state: directory
        owner: nginx
        group: nginx
    - name: Configure nginx
      template:
        src: graylog/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    # Keepalived
    - name: Install keepalived
      package:
        name: keepalived
        state: present
    - name: Configure keepalived
      template:
        src: graylog/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644
      notify: restart keepalived
    - name: Start keepalived
      service:
        name: keepalived
        state: started
        enabled: yes
