---

- name: restart redis instance
  systemd:
    name: redis_{{ redis_instance_restart }}.service
    state: restarted

- name: restart redis exporter instance
  systemd:
    name: redis_{{ redis_exporter_instance_restart }}.service
    state: restarted
