---

ntp_config_statistics: 'loopstats peerstats clockstats'

ntp_config_filegen:
  - 'loopstats file loopstats type day enable'
  - 'peerstats file peerstats type day enable'
  - 'clockstats file clockstats type day enable'

ntp_config_server:
  - '0.pool.ntp.org'
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'

ntp_config_restrict:
  - '-4 default kod notrap nomodify nopeer noquery limited'
  - '-6 default kod notrap nomodify nopeer noquery limited'
  - '127.0.0.1'
  - '::1'
  - 'source notrap nomodify noquery'

ntp_config_disable:
  - 'monitor'
