---

keepalived_vrrp_scripts:
  - name: 'chk_nginx'
    command: '/bin/killall -0 nginx'
    interval: 1
    weight: '-60'

keepalived_vrrp_instances:
  - name: 'VI_1'
    interface: 'eth0'
    state: 'BACKUP'
    virtual_router_id: '51'
    priority: '110'
    auth_type: 'PASS'
    auth_pass: 'password'
    track_script: 'chk_nginx'
    virtual_ipaddresses:
      - address: '192.168.122.24/24'
        interface: 'eth0'
      - address: '192.168.122.25/24'
        interface: 'eth0'
