---

# Graylog server
graylog_version: '3.3'
graylog_repository_package: "https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.rpm"
graylog_server_user: 'graylog'
graylog_server_group: 'graylog'
graylog_server_http_bind_address_ip: '0.0.0.0'
graylog_server_http_bind_address_port: '9000'
graylog_server_is_master: false
graylog_server_plugin_dir: '/usr/share/graylog-server/plugin'
graylog_server_timezone: 'UTC'
graylog_server_message_journal_dir: '/var/lib/graylog-server/journal'
graylog_server_processbuffer_processors: 5
graylog_server_outputbuffer_processors: 3
graylog_server_outputbuffer_processor_keep_alive_time: 5000
graylog_server_outputbuffer_processor_threads_core_pool_size: 3
graylog_server_outputbuffer_processor_threads_max_pool_size: 30

# Java process
graylog_server_min_heap: '1g'
graylog_server_max_heap: '1g'

# Elasticsearch configuration
graylog_server_elasticsearch_cluster_name: 'graylog-es-cluster'
graylog_server_elasticsearch_shards: 5
graylog_server_elasticsearch_replicas: 2

# MongoDB
graylog_server_mongodb_uri: "mongodb://127.0.0.1:27017/graylog"
