---

addresses:
  - ip: 192.168.10.20
    subnet: my_subnet_server
vm_size: Standard_E4ds_v4
osdisk_size: 30
osdisk_encrypt: true
disks:
  - name: disk1
    size: 200
    type: Premium_LRS
    encrypt: true
    lun: 0
    fstype: ext4
    mountpoint: /data

# If Azure start to choose the VM object id will have the uppercase
# Resource-Group-ID value, you must set this variable in order to ignore it,
# otherwise Terraform will always see a change in the VM (this is because M$
# treat the Resource-Group-ID as a case-insensitive value and Terraform work
# it as case-sensitive).
#azure_renamed_id: true
