---

# Configurations for MongoDB cluster
mongodb_master_node: "graylog-1" 
mongodb_nodes: "graylog-1,graylog-2,graylog-3"
# Config Server
mongodb_cs_bind_ip: "{{ graylog_mongodb_addr }}"
mongodb_cs_logpath: "/store/mongodb/cs/log"
mongodb_cs_dbpath: "/store/mongodb/cs/data"
mongodb_cs_replica_set_name: "configReplSet"
# Query Router
mongodb_qr_bind_ip: "{{ graylog_mongodb_addr }}"
mongodb_qr_logpath: "/store/mongodb/qr/log"
mongodb_qr_rs_nodes: "graylog-1:27019,graylog-2:27019,graylog-3:27019"
# Shard Node
mongodb_sn_bind_ip: "{{ graylog_mongodb_addr }}"
mongodb_sn_logpath: "/store/mongodb/sn/log"
mongodb_sn_dbpath: "/store/mongodb/sn/data"
mongodb_sn_replica_set_name: "graylog-shard-rs0"
