---

# Configurations for ElasticSearch cluster
es_repo_name: "6.x"
es_version: "6.8.10"
es_cluster_name: "graylog-es-cluster"
es_instance_name: "graylog-es-cluster1"
es_scripts: false
es_templates: false
es_version_lock: false
es_heap_size: "512m"
es_data_dirs:
  - "/store/elasticsearch/data"
es_log_dir: "/store/elasticsearch/log"
es_work_dir: "/store/elasticsearch/tmp"
es_bulk_queue_size: -1
es_config:
  cluster.name: "graylog-es-cluster"
  network.host:
    - "{{ ansible_eth0.ipv4.address }}"
    - "_local_"
  transport.host: "{{ graylog_elastic_addr }}"
  discovery.zen.ping.unicast.hosts:
    - 192.168.122.21
    - 192.168.122.22
    - 192.168.122.23
  http.port: 9200
  transport.tcp.port: 9300
  node.data: true
  node.master: true
  node.name: "{{ ansible_hostname }}"
  bootstrap.memory_lock: true
