---

redis_instances:
  - name: 'master'
    state: 'started'
    enabled: true
    user: 'redis'
    group: 'redis'
    config_path: '/etc'
    config_file: 'redis_master.conf'
    bind: '0.0.0.0'
    port: '6379'
    loglevel: 'warning'
    logfile: '/var/log/redis/redis_master.log'
    tcp_keepalive: '300'
    tcp_backlog: '65536'
    pidfile: '/var/run/redis_master_6379.pid'
    working_dir: '/var/lib/redis_master'
    maxmemory_policy: 'noeviction'
    cluster_enabled: 'yes'
    exporter_enabled: false
  - name: 'slave'
    state: 'started'
    enabled: true
    user: 'redis'
    group: 'redis'
    config_path: '/etc'
    config_file: 'redis_slave.conf'
    bind: '0.0.0.0'
    port: '6380'
    loglevel: 'warning'
    logfile: '/var/log/redis/redis_slave.log'
    tcp_keepalive: '300'
    tcp_backlog: '65536'
    pidfile: '/var/run/redis_slave_6380.pid'
    working_dir: '/var/lib/redis_slave'
    maxmemory_policy: 'noeviction'
    cluster_enabled: 'yes'
    exporter_enabled: false

# Note: Redis do not support hostnames, use IPs
redis_clusters:
  - name: redis_cluster
    nodes:
      - master: 192.168.122.50:6379
        slaves:
          - 192.168.122.51:6380
      - master: 192.168.122.51:6379
        slaves:
          - 192.168.122.52:6380
      - master: 192.168.122.52:6379
        slaves:
          - 192.168.122.50:6380
