---

- name: Check for MaxScale grants
  shell: |
    mysql -u root -e "show grants for {{ maxscale_monitor_user }}@{{ item.value }}"
  register: check_maxscale_grants
  with_dict: "{{ galera_interconnect_ips }}"
  changed_when: false
  ignore_errors: true

- block:
    - name: Deploy MaxScale SQL grants file
      template:
        src: roles/maxscale/templates/maxscale.sql.j2
        dest: /etc/maxscale.sql
        owner: root
        group: root
        mode: 0640

    - name: Create MaxScale permissions
      shell: |
        mysql -u root < /etc/maxscale.sql

    - name: Remove MaxScale SQL grants file
      file:
        path: /etc/maxscale.sql
        state: absent
  when:
    - check_maxscale_grants is failed
