---

- name: Adding MariaDB MaxScale yum repository
  yum_repository:
    name: maxscale
    description: MaxScale Yum Repository
    baseurl: "https://downloads.mariadb.com/MaxScale/{{ maxscale_version }}/centos/{{ ansible_distribution_major_version }}/x86_64"
    gpgkey: https://downloads.mariadb.com/MaxScale/MariaDB-MaxScale-GPG-KEY
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- block:
    - name: Get MaxScale APT repository key
      apt_key:
        url: "https://downloads.mariadb.com/MaxScale/{{ maxscale_version }}/MariaDB-Enterprise-Signing-Key.public"

    - name: Adding MaxScale apt repository
      apt_repository:
        repo: "deb https://downloads.mariadb.com/MaxScale/{{ maxscale_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
  when: ansible_os_family == "Debian"

- name: Installing MaxScale
  package:
    name: maxscale
    state: present

- name: Deploy MaxScale configuration file
  template:
    src: maxscale.cnf.j2
    dest: /etc/maxscale.cnf
    owner: root
    group: root
    mode: 0644

- name: Enable and start MaxScale service
  service:
    name: maxscale
    state: started
    enabled: yes
