---

- block:
    - name: "Download {{ maxscale_db_host.name }} ssl_ca_cert"
      get_url:
        url: "{{ maxscale_db_host.ssl_ca_cert.url }}"
        dest: "{{ maxscale_db_host.ssl_ca_cert.path }}"
      when:
        - maxscale_db_host.ssl_ca_cert.url is defined
        - maxscale_db_host.ssl_ca_cert.path is defined
    
    - name: "Download {{ maxscale_db_host.name }} ssl_cert"
      get_url:
        url: "{{ maxscale_db_host.ssl_cert.url }}"
        dest: "{{ maxscale_db_host.ssl_cert.path }}"
      when:
        - maxscale_db_host.ssl_cert.url is defined
        - maxscale_db_host.ssl_cert.path is defined
    
    - name: "Download {{ maxscale_db_host.name }} ssl_key"
      get_url:
        url: "{{ maxscale_db_host.ssl_key.url }}"
        dest: "{{ maxscale_db_host.ssl_key.path }}"
      when:
        - maxscale_db_host.ssl_key.url is defined
        - maxscale_db_host.ssl_key.path is defined
  when:
    - maxscale_db_host.ssl|bool
