---

- name: Install required packages
  package:
     name: "keepalived"
     state: present

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived

- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
