---

redis_server_bin: '/bin/redis-server'
redis_cli_bin: '/bin/redis-cli'

redis_exporter_enable: true
redis_exporter_bin: '/bin/redis_exporter'
redis_exporter_version: 'v1.9.0'
redis_exporter_arch: 'linux-amd64'
redis_exporter_download_url: "https://github.com/oliver006/redis_exporter/releases/download/{{ redis_exporter_version }}/redis_exporter-{{ redis_exporter_version }}.{{ redis_exporter_arch }}.tar.gz"

redis_instances:
  - name: 'default'
    state: 'started'
    enabled: true
    user: 'redis'
    group: 'redis'
    config_path: '/etc'
    config_file: 'redis.conf'
    bind: '0.0.0.0'
    port: '6379'
    loglevel: 'warning'
    logfile: '/var/log/redis/redis.log'
    tcp_keepalive: '300'
    tcp_backlog: '65536'
    pidfile: '/var/run/redis_6379.pid'
    working_dir: '/var/lib/redis'
    maxmemory_policy: 'noeviction'
    cluster_enabled: 'no'
    exporter_enabled: false

redis_RedHat_package: 'redis'
redis_RedHat_remi_package: 'http://rpms.remirepo.net/enterprise/remi-release-7.rpm'
redis_Debian_package: 'redis-server'

system_sysctls:
  vm.overcommit_memory: 1
  vm.swappiness: 0

system_systemd_onetime_services:
  - name: 'disable-thp'
    description: 'Disable Transparent Huge Pages (THP)'
    command: "/bin/sh -c \"echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag\""
    before_services:
      - "redis_default"
