---

- name: RedHat | Install MongoDB yum repository
  yum_repository:
    name: mongodb
    description: MongoDB YUM repo
    baseurl: "{{ mongodb_repository }}"
    gpgcheck: no

- name: RedHat | Install dependencies packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ mongodb_packages_dependencies }}"

- name: RedHat | Install Packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ mongodb_packages }}"
