---

- name: "Query for DB {{ mysql_database.name }} existence"
  command: "{{ mysql_command }} \"SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '{{ mysql_database.name }}';\""
  register: mysql_database_exists
  changed_when: false
  when:
    - mysql_database.name != '*'

- name: "DB {{ mysql_database.name }} status"
  debug:
    msg: "{{ mysql_database_exists.stdout }}"
  when:
    - mysql_database.name != '*'
    - just_verify|bool

- name: "Create DB {{ mysql_database.name }} if it does not exists"
  command: "{{ mysql_command }} \"CREATE DATABASE {{ mysql_database.name }};\""
  when:
    - mysql_database.name != '*'
    - mysql_database_exists.stdout == '0'
    - not just_verify|bool

- name: Manage DB grants
  include_tasks: manage_grants.yml
  with_items:
    - "{{ mysql_database.permissions }}"
  loop_control:
    loop_var: mysql_permission
