---

- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include_tasks: elasticsearch-optional-user.yml

#- name: Include specific Elasticsearch
#  include_tasks: "elasticsearch-{{ansible_os_family}}.yml"

#Install OS specific elasticsearch - this can be abbreviated in version 2.0.0
- name: Include specific Elasticsearch
  include_tasks: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include_tasks: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'
