---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- include_tasks: utilities-install.yml
  tags:
      - utilities

- name: check-set-parameters
  include_tasks: elasticsearch-parameters.yml
  tags:
      - always

- include_tasks: java.yml
  when: es_java_install
  tags:
      - java
- include_tasks: elasticsearch.yml
  tags:
      - install
- include_tasks: elasticsearch-config.yml
  tags:
      - config
- include_tasks: elasticsearch-scripts.yml
  when: es_scripts
  tags:
      - scripts
- include_tasks: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
  tags:
      - plugins
  #We always execute xpack as we may need to remove features
- include_tasks: xpack/elasticsearch-xpack.yml
  tags:
      - xpack
- include_tasks: elasticsearch-service.yml
  tags:
      - service
- include_tasks: elasticsearch-templates.yml
  when: es_templates
  tags:
      - templates
- meta: flush_handlers

