---
# Check for required variables

- name: Check graylog_server_password_secret Variable
  fail:
    msg: 'Variable graylog_server_password_secret required'
  when: graylog_server_password_secret is not defined

- name: Check graylog_server_admin_password Variable
  fail:
    msg: 'Variable graylog_server_admin_password required'
  when: graylog_server_admin_password is not defined

- name: Check graylog_server_elasticsearch_cluster_name variable
  fail:
    msg: 'Variable graylog_server_elasticsearch_cluster_name required'
  when: graylog_server_elasticsearch_cluster_name is not defined

- name: Check graylog_server_elasticsearch_hosts variable
  fail:
    msg: 'Variable graylog_server_elasticsearch_hosts required'
  when: graylog_server_elasticsearch_hosts is not defined

- name: Check graylog_server_mongodb_uri variable
  fail:
    msg: 'Variable graylog_server_mongodb_uri required'
  when: graylog_server_mongodb_uri is not defined

