---

- name: Install required packages
  package:
     name: "epel-release"
     state: present

- set_fact:
    disable_thp_before_services:
      - graylog-server

- name: Create disable Transparent Huge Pages (THP) systemd service
  template:
    src: disable-thp/disable-thp.service.j2
    dest: "/etc/systemd/system/disable-thp.service"
    owner: 'root'
    group: 'root'
    mode: 0644
  notify:
    -  reload systemd configuration

- name: Check disable Transparent Huge Pages (THP) systemd service
  service:
    name: 'disable-thp'
    state: 'started'
    enabled: true

- name: Set sysctl swappiness
  sysctl:
    name: vm.swappiness
    value: 20
    state: present
    reload: yes
    sysctl_set: yes

- name: Set sysctl tcp keepalive
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 300
    state: present

- name: "Build hosts file for main graylog group"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  with_items:
    - "{{ groups['graylog'] }}"

- name: "Build hosts file for backend interconnect graylog group"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].interconnect_addr }} {{ hostvars[item].interconnect_name }}$"
    line: "{{ hostvars[item].interconnect_addr }} {{ hostvars[item].interconnect_name }}"
    state: present
  with_items: "{{ groups['graylog_backend'] }}"
