---
# This role install and configure the graylog-server
- include_vars: ../../mongodb-cluster/defaults/main.yml

- name: Required Variables Check
  include_tasks: check_variables.yml

- name: Add Graylog Repository Key
  copy:
    src: RPM-GPG-KEY-graylog
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-graylog
    owner: root
    group: root
    mode: 0644

- name: Add Graylog Repository
  copy:
    src: graylog.repo
    dest: /etc/yum.repos.d/graylog.repo
    owner: root
    group: root
    mode: 0644

- name: Install Graylog Server
  yum:
    name: graylog-server
    state: installed

- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ graylog_server_user }}"
    group: "{{ graylog_server_group }}"
  with_items:
    - "{{ graylog_server_message_journal_dir }}"

- name: Configure Graylog Server
  template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
    owner: graylog
    group: graylog
    mode: 0644
  notify: restart graylog server

- name: Configure Graylog Server System Config
  template:
    src: graylog-server.j2
    dest: /etc/sysconfig/graylog-server
    owner: root
    group: root
    mode: 0644
  notify: restart graylog server
- name: Copy plugin file to the Graylog Server Plugin dir
  copy:
    src: "{{ item }}"
    dest: "{{ graylog_server_plugin_dir }}"
    mode: 0644
  with_fileglob:
    - files/plugin/*
  notify: restart graylog server
- name: Start Graylog Server
  service:
    name: graylog-server
    state: started
    enabled: yes
