---

- name: Required Variables Check
  include_tasks: check_variables.yml

- name: Add Graylog Repository package
  package:
    name: "{{ graylog_repository_package }}"
    state: installed

- name: Install Graylog Server
  yum:
    name: graylog-server
    state: installed

- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ graylog_server_user }}"
    group: "{{ graylog_server_group }}"
  with_items:
    - "{{ graylog_server_message_journal_dir }}"

- name: Configure Graylog Server
  template:
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
    owner: graylog
    group: graylog
    mode: 0644
  notify: restart graylog server

- name: Configure Graylog Server System Config
  template:
    src: graylog-server.j2
    dest: /etc/sysconfig/graylog-server
    owner: root
    group: root
    mode: 0644
  notify: restart graylog server

- name: Configure Graylog Server Log4j2 Config
  template:
    src: log4j2.xml.j2
    dest: /etc/graylog/server/log4j2.xml
    owner: root
    group: root
    mode: 0644
  notify: restart graylog server

- name: Copy plugin file to the Graylog Server Plugin dir
  copy:
    src: "{{ item }}"
    dest: "{{ graylog_server_plugin_dir }}"
    mode: 0644
  with_fileglob:
    - files/plugin/*
  notify: restart graylog server
